pipeline {
    agent any
    stages {
        stage('compile') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml -DskipTests clean package'
            }
        }
        stage('sonar-report') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml sonar:sonar'
            }
        }
        stage('deploy') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml -DskipTests deploy'
            }
        }

    }
}
