pipeline {
    agent any
    stages {
        stage('compile') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml -DskipTests clean package'
            }
        }
        stage('sonar-report') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml jacoco:prepare-agent install jacoco:report  -Daggregate=true jacoco:report-aggregate org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
            }
        }
        stage('deploy') {
            steps {
                sh 'mvn --file springbootwebapp/pom.xml -DskipTests deploy'
            }
        }

    }
}
